"""
Store various constants used across the data processing process.
"""

FISCAL_YEAR = 2024

# expected format:  Q<1-4> YYYY
LAST_QUARTERLY_SURVEY = "Q1 2025"
COUNT_GOVERNMENT_WIDE_YEARS_DISPLAYED = 5
COUNT_AGENCY_SPECIFIC_YEARS_DISPLAYED = 4
COUNT_AGENCY_SPECIFIC_YEARS_DISPLAYED_FOR_RECOVERY = 5
COUNT_PROGRAM_SPECIFIC_YEARS_DISPLAYED = 4